### PR TITLE
Show only total active events on home page

### PR DESCRIPTION
**Pull request by lucasrenan**
Bug fix: Show only active events total on home page.

### CODE REVIEW

**Comment by tauil** [comment]
👍  What do you think, @lucianosousa ?

**Comment by lucianosousa** [comment]
@tauil @lucasrenan,

Specifically about these commits, I always suggest create some rspec test for the new behavior.
--

I would say, we should improve this page a little more.

Nowadays, we do not return all active events in the list, just the `recent` ones.
We can improve this returning with pagination - or not - all active ones.

What you guys think about?

@lucasrenan do you have interest in make this list render all events?

**Comment by tauil** [comment]
I agree but if this is already a fix/improvement that is ok, I would merge this and do a quick planning for your other suggestion.

I also thought that it's missing a test for this but I didn't say anything because this is sort of a view/controller spec, right? I'm not sure if we have this kind of tests in the app but I'm all for creating a test for this. It's very simple!

**Comment by lucasrenan** [comment]
@tauil @lucianosousa actually, I tried to fix the N+1 queries that are being generated in the home page but could not fix them at all. this is just a simple fix for total active events, we could merge it and then open an issue to discuss the improvements we would make in the home page (including content, not only queries).

**Comment by lucianosousa** [comment]
@lucasrenan I would say that there is a test case pending here.
Can you add a test for this `@event_quantity` variable?

**Comment by lucasrenan** [comment]
@lucianosousa home controller specs added ;)

**Comment by tauil** [comment]
👍

**Pull request merged**
