### PR TITLE
Fix unexpected token error in proposals_helper.rb

### PR DESCRIPTION
**Pull request by lucasrenan**
Fix unexpected token error in `proposals_helper.rb` as reported by code climate:

https://codeclimate.com/github/call4paperz/call4paperz/app/helpers/proposals_helper.rb

### CODE REVIEW

**Comment by tauil** [comment]
👍

**Comment by lucasrenan** [comment]
@lucianosousa review, please :)

**Comment by lucianosousa** [comment]
@lucasrenan @tauil it's a ruby 2.3 syntax.
I think we should update codeclimate config to not raise a warning on it.

**Comment by lucianosousa** [comment]
@lucasrenan @tauil as you can see here in this branch(https://codeclimate.com/github/call4paperz/call4paperz/compare/codeclimate-ruby-update)
It's is fixed because now recognize the ruby 2.3

So, I prefer merge the other PR and close this one.
What you guys think about?

**Comment by lucasrenan** [comment]
@lucianosousa go ahead, merge the other one :D

**Pull request closed without merging**
