### PR TITLE
fix datepicker date format

### PR DESCRIPTION
**Pull request by lucianosousa**

### CODE REVIEW

**Comment by lucianosousa** [comment]
@tauil can u take a look on it?

**Comment by tauil** [comment]
:+1:

**Comment by lucianosousa** [comment]
@tauil Did you merge this? I couldnt see it on master

**Comment by tauil** [comment]
Damn! I did not and it's not supposed to be closed. Maybe when I killed the branch `rv-rails4` it closed automatically this issue instead of change the branch to master. :disappointed: 

Well, can you open this again agaist branch `master`?

**Pull request closed without merging**
