### PR TITLE
Clean up comments_controller.rb

### PR DESCRIPTION
**Pull request by lucasrenan**
Call4paperz only allows users to create comments, so this PR cleans up `comments_controller.rb`

### CODE REVIEW

**Comment by lucianosousa** [comment]
@lucasrenan you can also remove the
`respond_to` line. Since we do not use something different than html

@tauil any thoughts?

**Comment by lucasrenan** [comment]
@lucianosousa actually,this is a first major clean up, I'm not pretty confident about removing `respond_to` blocks, we may do it in another PR.

**Comment by lucianosousa** [comment]
👍 for me.

@tauil

**Comment by lucasrenan** [comment]
@tauil any concerns?

**Comment by tauil** [comment]
👍  I would like to see the `respond_to` refactored also.. 😄

**Comment by lucasrenan** [comment]
@tauil I can remove the `respond_to` blocks in another PR :)

**Comment by tauil** [comment]
👍

**Pull request merged**
