### PR TITLE
Remove Gemnasium badge

### PR DESCRIPTION
**Pull request by lucasrenan**
Gemnasium was acquired by Gitlab and is now dead.

### CODE REVIEW

**Comment by lucianosousa** [comment]
@lucasrenan I think I've updated the circle ci build. can you jus do a push -f here only to rerun the workflow?

**Comment by lucasrenan** [comment]
@lucianosousa apparently, it's still triggering the travis build

**Comment by lucasrenan** [comment]
@gustavokloh we will need your help :)

**Comment by gustavokloh** [comment]
@lucasrenan what's happening?

**Comment by lucianosousa** [comment]
@gustavokloh travis-ci is still running to catch builds, I've disabled it but didn't stop

**Comment by lucasrenan** [comment]
closing in favor of https://github.com/call4paperz/call4paperz/pull/254

**Pull request closed without merging**
