### PR TITLE
Update readme for docker

### PR DESCRIPTION
**Pull request by kleberngueriero**
Update README.md to explain better the steps needed to run the application using Docker in development and add the tested Docker versions.

related to #189

### CODE REVIEW

**Comment by kleberngueriero** [comment]
@lucianosousa @lucasrenan @tauil , could you review it?

**Comment by tauil** [comment]
👍

**Comment by lucianosousa** [comment]
I'll test it today and tell my thoughts

**Comment by lucianosousa** [comment]
Good job guys, work like a charm!

Thanks for all.

**Pull request merged**
