### PR TITLE
Update docker configs and use ruby:2.4.1-slim image

### PR DESCRIPTION
**Pull request by lucasrenan**
Small improvements for development env with docker:

- use slim image, which is a bit smaller. the final image size is around: 900MB (before it was larger than 1GB)
- use a volume for gems caching
- fix gem bullet dependency `uniform_notifier (~> 1.10.0)`

### CODE REVIEW

**Comment by lucasrenan** [comment]
@lucianosousa @tauil not sure why, but looks like something is wrong with travis config...

looking to this build (from @tauil) https://travis-ci.org/call4paperz/call4paperz/builds/290529597
I see:
```
Setting environment variables from repository settings
$ export RECAPTCHA_PRIVATE_KEY=[secure]
$ export RECAPTCHA_PUBLIC_KEY=[secure]
```

but I'm not seeing it on my current builds like this one: https://travis-ci.org/call4paperz/call4paperz/builds/290950746

**Comment by tauil** [comment]
@lucasrenan yeah. I just noticed that in the other PR. No idea what's happening. We'll need to investigate. I'll spend some more time on this project this next week, if you guys wanna talk about it, let me know. At least to prioritize tasks.

**Comment by lucasrenan** [comment]
@tauil I guess travis is exporting recaptcha env vars for you and @lucianosousa but not for me.

I can reproduce the failing build in my local env removing recaptcha env vars.

**Comment by tauil** [comment]
Take a look at [this PR](https://github.com/call4paperz/call4paperz/pull/218) and test if this fixes your issue.

**Comment by lucasrenan** [comment]
@tauil maybe I can add the keys here https://github.com/call4paperz/call4paperz/blob/master/.travis.yml#L8

maybe any value would work for our current test suit.

**Comment by lucianosousa** [comment]
I'll have a look this week. seems good a deep test

**Comment by tauil** [comment]
@lucasrenan that doesn't make much sense because the file is the same for you and me but my branches/commits don't fail.

**Comment by lucasrenan** [comment]
@tauil @lucianosousa build is green :)

**Comment by lucianosousa** [comment]
Already tested here and looks sweet <3

cc @tauil

**Comment by tauil** [comment]
I'm not using docker at the moment. Go ahead and merge it! I trust you! :+1:

**Pull request merged**
