### PR TITLE
fixing issue #181: profile image broke layout

### PR DESCRIPTION
**Pull request by hugonomura**
Fixing the issue #181

### CODE REVIEW

**Comment by lucianosousa** [comment]
@hugonomura can you plz upload here an printscreen?

**Comment by hugonomura** [comment]
Sure @lucianosousa 

**Home**
home

**Events page**
events-page

I just change this properties in inspect element of my browser, but I think it ok, right?

**Comment by lucianosousa** [comment]
@hugonomura it could be better. the old image size was far better
I' not sure, but I think there is something related to this PR: https://github.com/call4paperz/call4paperz/pull/177

**Comment by lucianosousa** [comment]
more infos here: https://github.com/call4paperz/call4paperz/issues/138

**Comment by hugonomura** [comment]
Hi @lucianosousa 
I made the suggested changes in user image.
Please, can you take a look?

The results of my changes can see in images above.
**Home**
Changes in Home
home

**Events page**
Changes in events page
events_page

**User Profile**
No impact in the user profile page
user-page

**Comment by lucianosousa** [comment]
@hugonomura awesome! can I suggest just one more thing? Can you put the https://github.com/call4paperz/call4paperz/blob/master/app/assets/images/no_avatar.png back when there is none profile image?

**Comment by hugonomura** [comment]
Sure @lucianosousa 

I think which I found the root cause, but I need configure my environment to test the fix.
I will make this and submit a new commit  in this PR with the fix.

**Comment by lucianosousa** [comment]
@hugonomura cheers! I' waiting here

**Comment by hugonomura** [comment]
Please, ignore the last commit, I just forced this, because I used the wrong email account in my last commit.

**Comment by lucianosousa** [comment]
@hugonomura let me know when you finish. when it' done, can you put a print here?
tks

**Comment by hugonomura** [comment]
Hi @lucianosousa 
I made some changes running the code on my machine, but i cannot reproduce the problem with missing images (user and images).
In my understand, the problem is related with this: http://stackoverflow.com/questions/19017137/rails-4-image-tag-is-not-linking-to-my-digested-image-assets/19232244#19232244
Do you agree with me?
I am trying to change some configurations at my development.rb file, but I don't know what I need do to reproduce this on my local machine. Could you (or anyone) help me with this? :)

**Comment by lucasrenan** [comment]
@lucianosousa @hugonomura here it's the fix for `no avatar` default image in production https://github.com/call4paperz/call4paperz/pull/186

**Comment by lucianosousa** [comment]
@lucasrenan tks for the PR. Already merged.
@hugonomura CSS on home is the same, also the border on profile images(events page)
I think this is our biggest challenge to fix now. ;)

screen shot 2016-10-29 at 11 37 29

**Comment by lucianosousa** [comment]
@hugonomura do u have a print for this issue?

**Comment by hugonomura** [comment]
@lucianosousa you can see the result on https://github.com/call4paperz/call4paperz/pull/182#issuecomment-256404146
It is the same code, I don't made any changes on scss file after that.

**Comment by lucianosousa** [comment]
screen shot 2016-11-04 at 19 28 54

deployed.
almost good.

I think we should improve the rescue image.t

thanks for the commit ;)

**Comment by lucasrenan** [comment]
@lucianosousa looks like the right image is the "default no avatar", we may change the user avatar image size. this way, text can be aligned with image.

**Comment by lucianosousa** [comment]
@lucascaton that' right. @tauil can you help us on this?

**Comment by tauil** [comment]
What's the issue? The size of the image?

**Comment by lucascaton** [comment]
@lucianosousa I think you meant @lucasrenan 😁

**Comment by lucianosousa** [comment]
@lucascaton sure. sorry! :)

**Pull request merged**
