### PR TITLE
profile css improved

### PR DESCRIPTION
**Pull request by Vitormdias**

### CODE REVIEW

**Comment by lucianosousa** [comment]
@Vitormdias can you post here a before/after print?

**Comment by lucianosousa** [comment]
also, you can remove the bin/setup change, it's merged in another PR

**Comment by tauil** [comment]
A before and after print would really be great to speed up the review process.

**Comment by Vitormdias** [comment]
Antes
captura de tela de 2016-10-10 14-01-54

Depois
captura de tela de 2016-10-10 14-02-27

**Comment by tauil** [comment]
What is this `LGTM` that you write eveytime? @lucasrenan

**Comment by lucasrenan** [comment]
@tauil it is Looks Good To Me 💃

**Pull request merged**
