### PR TITLE
add @lucasrenan as contributor

### PR DESCRIPTION
**Pull request by lucianosousa**

### CODE REVIEW

**Comment by lucianosousa** [comment]
@tauil any oposition?

**Comment by rodrigopinto** [comment]
What do you think about to point contributors list to the [contributors graph](https://github.com/call4paperz/call4paperz/graphs/contributors) and only keep up to date the current maintainers?

**Comment by tauil** [comment]
I would vote to use the @rodrigopinto suggestions and maybe mention the current active maintainers.

**Comment by lucasrenan** [comment]
I also agree with @rodrigopinto :)

anyway, thanks to mention @lucianosousa

**Comment by lucianosousa** [comment]
updated

**Comment by tauil** [comment]
👍

**Pull request merged**
