### PR TITLE
Remove xml responses in controllers

### LINKED ISSUE #159: Does controllers need to respond to xml?
I'm seeing a lot of `render :xml` do we need them? do we need to respond anything else than `html`?

### PR DESCRIPTION
**Pull request by lucasrenan**
Looks like the app is not responding to xml

closes #159

### CODE REVIEW

**Comment by lucianosousa** [comment]
@lucasrenan Can you also remove the `respond_to` lines?

@tauil do you agree with that?

**Comment by lucasrenan** [comment]
@lucianosousa I'm not pretty confident in removing `respond_to` yet. firstly, I'm doing a major cleanup and then we can figure out a safe way to do it.

**Comment by tauil** [comment]
I would vote to also refactor `respond_to` and use `respond_with`

**Comment by lucasrenan** [comment]
@tauil I can do it in another PR :)

**Comment by tauil** [comment]
👍

**Pull request merged**
