### PR TITLE
Bumping rails to 4.2

### PR DESCRIPTION
**Pull request by ricardovaleriano**
:warning: [ WIP ]

TODO:

  - [x] Check the datepicker date format (apparently, isn't working as expected anymore).

### CODE REVIEW

**Comment by ricardovaleriano** [comment]
I'm waiting for the CI.
Then I'll will wait some time for code reviews, but I think that this is it. So please, be fast on review this because I'm shipping it! XD

**Comment by lucianosousa** [comment]
o/

**Comment by lucianosousa** [comment]
@ricardovaleriano what about it?

**Comment by lucianosousa** [comment]
#109 fixes it

**Comment by lucianosousa** [comment]
@andrefonseca @tauil can u take a look on it?

**Comment by aoqfonseca** [comment]
ok for me

**Comment by lucianosousa** [comment]
@viniciussbs

**Comment by tauil** [comment]
:+1:

**Pull request merged**
