### PR TITLE
Update ruby version 2.5.1 to 2.6.5

### PR DESCRIPTION
**Pull request by frankyston**
Update ruby version 2.5.1 to 2.6.5

### CODE REVIEW

**Comment by frankyston** [comment]
Do not fix Hakiri as there is this PR https://github.com/call4paperz/call4paperz/pull/329 that solves this problem.

**Comment by lucasrenan** [comment]
@frankyston I'll test it as soon as possible.

**Comment by frankyston** [comment]
> I'll test it as soon as possible.

Thanks 😄

**Comment by diegopolido** [comment]
> it works on my machine

I've created an app to test it on Heroku and it's working: https://c4p-cedar-staging.herokuapp.com/

**Comment by diegopolido** [comment]
@lucasrenan could you please review this PR https://github.com/call4paperz/call4paperz/pull/329 to merge it before this one?

**Comment by frankyston** [comment]
@diegopolido and @lucasrenan I can merge?

**Comment by lucasrenan** [comment]
@diegopolido #329 is merged already 🤷‍♂

**Comment by diegopolido** [comment]
@frankyston :rocket:

**Pull request merged**
