### PR TITLE
Add app volume to docker-compose config

### PR DESCRIPTION
**Pull request by lucasrenan**
Add volume to docker-compose config. Files sync were not working without this config.

related to https://github.com/call4paperz/call4paperz/pull/189

### CODE REVIEW

**Comment by lucasrenan** [comment]
@kleberngueriero @lucianosousa review please!

**Comment by kleberngueriero** [comment]
@lucasrenan, I added a volume to the app in docker-compose.override.yml.sample.
So, If you do a `cp docker-compose.override.sample.yml docker-compose.override.yml` and then try to run the application, it's gonna use the volume and sync files.

The reason I didn't put the volume in docker-compose.yml, but I put it in its override file, is to make default docker-compose.yml more generic(so you wouldn't use a volume in production, for example).

**Comment by lucasrenan** [comment]
@kleberngueriero I got it, should I close this PR?

**Comment by lucianosousa** [comment]
@kleberngueriero please, describe this in the readme file or other config file.
See the example how to run using `bin/setup` file.

We need keep all these basic config well documented to keep the boot easier as possible for new users. ;)

**Comment by lucianosousa** [comment]
so guys, what should I do with this PR? as I said in another issue here, I couldn't run the app following the default steps for docker. I don't know if this will help the current workflow or not

**Comment by tauil** [comment]
Make sure to have all steps documented and all versions tracked in the docs also.

**Comment by kleberngueriero** [comment]
I'm going to create a new branch to update the README.

**Comment by lucasrenan** [comment]
@kleberngueriero may I close this PR?

**Comment by kleberngueriero** [comment]
@lucasrenan Yeah, I think you can close it.

**Pull request closed without merging**
