### PR TITLE
Remove useless private modifier in vote.rb

### PR DESCRIPTION
**Pull request by lucasrenan**
Remove useless private modifier in vote.rb reported by code climate: 

https://codeclimate.com/github/call4paperz/call4paperz/app/models/vote.rb

### CODE REVIEW

**Comment by lucasrenan** [comment]
@lucianosousa @tauil review, please :)

**Comment by tauil** [comment]
It's not useless. I agree with the `private`. The public method should be `like` and `dislike` only. Those are the public interface for this class, why to expose also `vote` method?

**Comment by lucasrenan** [comment]
@tauil actually,  `private` is probably not making `self.vote` private, I will use `private_class_method` instead.

**Comment by lucianosousa** [comment]
I get it.
`Vote.vote` works on console.

Nice to know it.
Thanks for this PR.

**Pull request merged**
