### PR TITLE
Renames the project

### PR DESCRIPTION
**Pull request by ricardovaleriano**
closes the #99.

### CODE REVIEW

**Comment by tauil** [comment]
This is more than rename the project, but it's ok to me due it's already done and it's an old issue and solution! :+1:

**Comment by rodrigopinto** [comment]
@tauil Why not remove @lucianosousa commits? Idea, keep just the project rename, create a different PR with versions update and merge, after all rebase it.

**Comment by tauil** [comment]
That an idea, what do you think, @lucianosousa ?

**Comment by lucianosousa** [comment]
Agree.
I supposed this branch were merge in master with rv4 branch.
Doing it here

**Pull request merged**
